version: '3.2'

services:
  mongo:
    image: poetapp/mongo-ci:4.0.6
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    #volumes:
    #  - db:/data/db
    #  - ./mongodb:/docker-entrypoint-initdb.d

  rabbit:
    image: rabbitmq:3
    ports:
      - "5671:5671"
      - "5672:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=some_secret_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminPass

  ipfs:
    image: ipfs/go-ipfs:v0.4.18
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    #volumes:
    #  - data:/data/ipfs

  bitcoind-1:
    image: ruimarinho/bitcoin-core:0.17.0
    ports:
      - "18443:18443"
    #volumes:
    #  - type: tmpfs
    #    target: /home/bitcoin/.bitcoin
    restart: always
    command:
      -printtoconsole
      -server
      -regtest=1
      -rpcuser=bitcoinrpcuser
      -rpcpassword=bitcoinrpcpassword
      -rpcallowip=::/0
      -deprecatedrpc=signrawtransaction

  bitcoind-2:
    image: ruimarinho/bitcoin-core:0.17.0
    ports:
      - "19443:18443"
    #volumes:
    #  - type: tmpfs
    #    target: /home/bitcoin/.bitcoin
    restart: always
    command:
      -printtoconsole
      -server
      -regtest=1
      -rpcuser=bitcoinrpcuser
      -rpcpassword=bitcoinrpcpassword
      -rpcallowip=::/0
      -deprecatedrpc=signrawtransaction

  poet-node:
    build: .
    ports:
      - "18080:18080"
    depends_on:
      - mongo
      - rabbit
      - ipfs
      - bitcoind-1
      - bitcoind-2
    environment:
      - POET_SERVICE=node
      - BITCOIN_URL=bitcoind-1
      - BITCOIN_URL_B=bitcoind-2
      - RABBITMQ_URL=amqp://admin:adminPass@rabbit
      - MONGODB_HOST=mongo
      - MONGODB_USER=poet
      - MONGODB_PASSWORD=poetPass
      - MONGODB_DATABASE=poet
      - IPFS_URL=http://ipfs:5001
      - IPFS_ARCHIVE_URL_PREFIX=http://ipfs:8080/ipfs
      - INTEGRATION_TEST_NODE_URL=http://poet-node:18080
      - LOGGING_LEVEL=trace
    links:
      - mongo
      - rabbit
      - ipfs
    command: ["-c", "/wait-for-it.sh rabbit:5672 && npm run start"]
    entrypoint: ["/bin/sh"]

  poet-node-blockchain-writer:
    build: .
    depends_on:
      - mongo
      - rabbit
      - bitcoind-1
      - bitcoind-2
    environment:
      - POET_SERVICE=blockchain-writer
      - BITCOIN_URL=bitcoind-1
      - BITCOIN_URL_B=bitcoind-2
      - RABBITMQ_URL=amqp://admin:adminPass@rabbit
      - MONGODB_HOST=mongo
      - MONGODB_USER=poet
      - MONGODB_PASSWORD=poetPass
      - MONGODB_DATABASE=poet
      - LOGGING_LEVEL=trace
    links:
      - mongo
      - rabbit
      - bitcoind-1
      - bitcoind-2
    command: ["-c", "/wait-for-it.sh rabbit:5672 && npm run start:blockchain-writer"]
    entrypoint: ["/bin/sh"]

#volumes:
#  db:
#    driver: local
#
#  data:
#    driver: local
