version: 2 
jobs: 
 build: 
   docker: 
     # DLC does nothing here, its caching depends on commonality of the image layers.
     - image: circleci/node:10.14.2
   steps: 
     - checkout 
     - setup_remote_docker: 
         docker_layer_caching: true 
     # DLC will explicitly cache layers here and try to avoid rebuilding.
     - run: docker-compose up -d
     - run: docker images
     - run: docker ps -a
     - run: docker-compose logs poet-node
     - run: docker-compose exec poet-node npm run lint
     - run: docker-compose exec poet-node npm run coverage
