version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: poetapp/node
    docker:
      - image: poetapp/base:10.14.2-alpine
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  lint:
    executor: docker-publisher
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: npm run lint
  test:
    executor: docker-publisher
    docker:
      - image: mongo:3.7
      - image: rabbitmq:3
      - image: ipfs/go-ipfs:v0.4.18
      - image: ruimarinho/bitcoin-core:0.17.0
        command: |       
          -printtoconsole
          -server
          -regtest=1
          -rpcuser=bitcoinrpcuser
          -rpcpassword=bitcoinrpcpassword
          -rpcallowip=::/0
          -deprecatedrpc=signrawtransaction

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Generate code coverage
          command: npm run coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master