version: 2.1
executors:
  base-node:
    environment:
      IMAGE_NAME: poetapp/node
    docker:
      - image: poetapp/base:10.14.2-alpine 
      
  coverage-builder:
    environment:
      IMAGE_NAME: poetapp/node
      DOCKERIZE_VERSION: v0.3.0

    docker:
      - image: poetapp/base:10.14.2-alpine

      # this containers make up the node dep services, which run in the primary container      
      - name: poet-node
        image: poetapp/mongo-ci:4.0.6

      - name: rabbit
        image: rabbitmq:3
        environment:
          RABBITMQ_ERLANG_COOKIE: some_secret_cookie
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: adminPass
        
      - name: ipfs
        image: ipfs/go-ipfs:v0.4.18

      - name: bitcoind-1
        image: ruimarinho/bitcoin-core:0.17.0
        command: [
          "-printtoconsole",
          "-server",
          "-regtest=1",
          "-rpcuser=bitcoinrpcuser",
          "-rpcpassword=bitcoinrpcpassword",
          "-rpcallowip=::/0",
          "-deprecatedrpc=signrawtransaction"
        ]

      - name: bitcoind-2
        image: ruimarinho/bitcoin-core:0.17.0
        command: [
          "-printtoconsole",
          "-server",
          "-regtest=1",
          "-rpcuser=bitcoinrpcuser",
          "-rpcpassword=bitcoinrpcpassword",
          "-rpcallowip=::/0",
          "-deprecatedrpc=signrawtransaction",
          "-port=19443"
        ]

jobs:
  build:
    executor: base-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  lint:
    executor: base-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run lint in container
          command: npm run lint

  coverage:
    environment:
      MONGODB_USER: "poet"
      MONGODB_PASSWORD: "poetPass"
      MONGODB_DATABASE: "poet"
      MONGODB_HOST: mongo
      POET_SERVICE: node
      RABBITMQ_URL: amqp://admin:adminPass@rabbit
      IPFS_URL: http://ipfs:5001
      IPFS_ARCHIVE_URL_PREFIX: http://ipfs:8080/ipfs
      INTEGRATION_TEST_NODE_URL: http:/localhost:18080
      BITCOIN_URL: "bitcoind-1"
      BITCOIN_URL_B: "bitcoind-2"
    executor: coverage-builder
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build dist
          command: npm run build
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz            
      - run:
          name: Wait for rabbitmq
          command: dockerize -wait tcp://rabbit:5672 -timeout 1m
      - run:
          name: start node
          command: npm run start
          background: true
      - run:
          name: Wait for node
          command: dockerize -wait http://localhost:18080/health -timeout 1m
      - run:
          name: Run coverage in container
          command: npm run coverage


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
          filters:
            branches:
              only: master
      - coverage:
          requires:
            - build
          filters:
            branches:
              only: master